<?php

/**
 * BaseMensajeRespuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tema
 * @property integer $id_seccion
 * @property MensajeTema $MensajeTema
 * @property Seccion $Seccion
 * @property sfGuardUser $creado_por
 * 
 * @method integer          getIdTema()      Returns the current record's "id_tema" value
 * @method integer          getIdSeccion()   Returns the current record's "id_seccion" value
 * @method MensajeTema      getMensajeTema() Returns the current record's "MensajeTema" value
 * @method Seccion          getSeccion()     Returns the current record's "Seccion" value
 * @method sfGuardUser      getCreadoPor()   Returns the current record's "creado_por" value
 * @method MensajeRespuesta setIdTema()      Sets the current record's "id_tema" value
 * @method MensajeRespuesta setIdSeccion()   Sets the current record's "id_seccion" value
 * @method MensajeRespuesta setMensajeTema() Sets the current record's "MensajeTema" value
 * @method MensajeRespuesta setSeccion()     Sets the current record's "Seccion" value
 * @method MensajeRespuesta setCreadoPor()   Sets the current record's "creado_por" value
 * 
 * @package    sfforo
 * @subpackage model
 * @author     Daniel López
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMensajeRespuesta extends Mensaje
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('mensaje_respuesta');
        $this->hasColumn('id_tema', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_seccion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MensajeTema', array(
             'local' => 'id_tema',
             'foreign' => 'id'));

        $this->hasOne('Seccion', array(
             'local' => 'id_seccion',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as creado_por', array(
             'local' => 'id_autor',
             'foreign' => 'id'));
    }
}