<?php

/**
 * BaseRol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $Usuarios
 * 
 * @method string              getNombre()   Returns the current record's "nombre" value
 * @method Doctrine_Collection getUsuarios() Returns the current record's "Usuarios" collection
 * @method Rol                 setNombre()   Sets the current record's "nombre" value
 * @method Rol                 setUsuarios() Sets the current record's "Usuarios" collection
 * 
 * @package    sfforo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rol');
        $this->hasColumn('nombre', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Usuario as Usuarios', array(
             'local' => 'id',
             'foreign' => 'id_rol'));
    }
}