<?php

/**
 * BaseMensaje
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $contenido
 * @property integer $id_autor
 * @property sfGuardUser $Autor
 * 
 * @method clob        getContenido() Returns the current record's "contenido" value
 * @method integer     getIdAutor()   Returns the current record's "id_autor" value
 * @method sfGuardUser getAutor()     Returns the current record's "Autor" value
 * @method Mensaje     setContenido() Sets the current record's "contenido" value
 * @method Mensaje     setIdAutor()   Sets the current record's "id_autor" value
 * @method Mensaje     setAutor()     Sets the current record's "Autor" value
 * 
 * @package    sfforo
 * @subpackage model
 * @author     Daniel López
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMensaje extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mensaje');
        $this->hasColumn('contenido', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('id_autor', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Autor', array(
             'local' => 'id_autor',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}