<?php

/**
 * BaseMensajeRespuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_tema
 * @property MensajeTema $MensajeTema
 * 
 * @method integer          getIdTema()      Returns the current record's "id_tema" value
 * @method MensajeTema      getMensajeTema() Returns the current record's "MensajeTema" value
 * @method MensajeRespuesta setIdTema()      Sets the current record's "id_tema" value
 * @method MensajeRespuesta setMensajeTema() Sets the current record's "MensajeTema" value
 * 
 * @package    sfforo
 * @subpackage model
 * @author     Daniel López
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMensajeRespuesta extends Mensaje
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('mensaje_respuesta');
        $this->hasColumn('id_tema', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MensajeTema', array(
             'local' => 'id_tema',
             'foreign' => 'id'));
    }
}