<?php

/**
 * BaseMensajeTema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property integer $id_seccion
 * @property boolean $fijo
 * @property Seccion $Seccion
 * @property sfGuardUser $creado_por
 * @property Doctrine_Collection $Respuestas
 * 
 * @method string              getTitulo()     Returns the current record's "titulo" value
 * @method integer             getIdSeccion()  Returns the current record's "id_seccion" value
 * @method boolean             getFijo()       Returns the current record's "fijo" value
 * @method Seccion             getSeccion()    Returns the current record's "Seccion" value
 * @method sfGuardUser         getCreadoPor()  Returns the current record's "creado_por" value
 * @method Doctrine_Collection getRespuestas() Returns the current record's "Respuestas" collection
 * @method MensajeTema         setTitulo()     Sets the current record's "titulo" value
 * @method MensajeTema         setIdSeccion()  Sets the current record's "id_seccion" value
 * @method MensajeTema         setFijo()       Sets the current record's "fijo" value
 * @method MensajeTema         setSeccion()    Sets the current record's "Seccion" value
 * @method MensajeTema         setCreadoPor()  Sets the current record's "creado_por" value
 * @method MensajeTema         setRespuestas() Sets the current record's "Respuestas" collection
 * 
 * @package    sfforo
 * @subpackage model
 * @author     Daniel López
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMensajeTema extends Mensaje
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('mensaje_tema');
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('id_seccion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fijo', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Seccion', array(
             'local' => 'id_seccion',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as creado_por', array(
             'local' => 'id_autor',
             'foreign' => 'id'));

        $this->hasMany('MensajeRespuesta as Respuestas', array(
             'local' => 'id',
             'foreign' => 'id_tema'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'titulo',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}