<?php

/**
 * BaseMensajePrivado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property integer $id_destinatario
 * @property Usuario $Usuario
 * 
 * @method string         getTitulo()          Returns the current record's "titulo" value
 * @method integer        getIdDestinatario()  Returns the current record's "id_destinatario" value
 * @method Usuario        getUsuario()         Returns the current record's "Usuario" value
 * @method MensajePrivado setTitulo()          Sets the current record's "titulo" value
 * @method MensajePrivado setIdDestinatario()  Sets the current record's "id_destinatario" value
 * @method MensajePrivado setUsuario()         Sets the current record's "Usuario" value
 * 
 * @package    sfforo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMensajePrivado extends Mensaje
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('mensaje_privado');
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('id_destinatario', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'id_destinatario',
             'foreign' => 'id'));
    }
}