<?php

/**
 * BaseSeccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $Temas
 * 
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getTemas()       Returns the current record's "Temas" collection
 * @method Seccion             setNombre()      Sets the current record's "nombre" value
 * @method Seccion             setDescripcion() Sets the current record's "descripcion" value
 * @method Seccion             setTemas()       Sets the current record's "Temas" collection
 * 
 * @package    sfforo
 * @subpackage model
 * @author     Daniel López
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seccion');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MensajeTema as Temas', array(
             'local' => 'id',
             'foreign' => 'id_seccion'));
    }
}