<?php

/**
 * MensajeRespuestaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MensajeRespuestaTable extends MensajeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MensajeRespuestaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MensajeRespuesta');
    }
}