<?php

/**
 * MensajePrivadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MensajePrivadoTable extends MensajeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object MensajePrivadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MensajePrivado');
    }
}