<?php

/**
 * MensajeTema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfforo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MensajeTema extends BaseMensajeTema
{

  public function getUltimaRespuesta()
  {
    return Doctrine::getTable('MensajeRespuesta')
      ->createQuery('r')
      ->where('r.id_tema = ?', $this->getId())
      ->orderBy('r.created_at DESC')
      ->fetchOne();
  }

  public function esFijo()
  {
    return $this->getFijo();
  }
}
