<?php

/**
 * Seccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sfforo
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Seccion extends BaseSeccion
{

  public function getTemasTotales()
  {
    return count($this->getTemas());
  }

  public function getTemasOrdenados()
  {
    return Doctrine_Core::getTable('MensajeTema')
      ->createQuery('t')
      ->where('t.id_seccion = ?', $this->getId())
      ->innerJoin('t.MensajeRespuesta r')
      ->orderBy('r.created_at DESC, t.created_at DESC')
      ->execute();
  }

  public function getMensajesTotales()
  {
    return $this->getTemasTotales() + count(
      Doctrine::getTable('MensajeRespuesta')
      ->createQuery('r')
      ->where('r.id_seccion = ?', $this->getId())
      ->execute()
      );
  }

  public function getUltimoMensaje()
  {
    $ultimoTema = Doctrine::getTable('MensajeTema')
      ->createQuery('t')
      ->where('t.id_seccion = ?', $this->getId())
      ->orderBy('t.created_at DESC')
      ->fetchOne();
    $ultimaRespuesta = Doctrine::getTable('MensajeRespuesta')
      ->createQuery('r')
      ->where('r.id_seccion = ?', $this->getId())
      ->orderBy('r.created_at DESC')
      ->fetchOne();
    $ultimo = (new DateTime($ultimoTema->getCreatedAt()) > new DateTime($ultimaRespuesta->getCreatedAt())) ? $ultimoTema : $ultimaRespuesta;
    return $ultimo;
  }
}
