# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:        /
  param:      { module: home, action: index }

fijar_tema:
  url:        /seccion/:slug_seccion/fijar_tema/:slug_tema
  param:      { module: tema, action: fijar }

sf_guard_forgot_password:
  url:        /contrasena_olvidada
  param:      { module: home, action: index }

sf_guard_register:
  url:        /nuevo_usuario
  param:      { module: usuario, action: new }

sf_guard_signin:
  url:        /comprobar_login
  param:      { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:        /logout
  param:      { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:        /request_password
  param:      { module: sfGuardAuth, action: password }

editar_usuario:
  url:        /editar_usu/:id
  param:      { module: usuario, action: edit}

registro_usuarios:
  url:        /nuevo_usuario
  param:      { module: usuario, action: new }

login:
  url:        /login
  param:      { module: sfGuardAuth, action: signin }

form_nueva_respuesta:
  url:        /seccion/:slug_seccion/:slug_tema/nueva_respuesta
  param:      { module: respuesta, action: new }

ver_tema:
  url:        /seccion/:slug_seccion/ver_tema/:slug_tema
  param:      { module: tema, action: index }

insertar_nuevo_tema:
  url:        /seccion/:slug/create
  param:      { module: seccion, action: create }

form_nuevo_tema:
  url:        /seccion/:slug/nuevo_tema
  param:      { module: seccion, action: new }

ver_seccion:
  url:        /seccion/:slug_seccion
  param:      { module: seccion, action: index }

tema:
  url:        /tema/:id
  param:      { module: tema, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:        /:module
  param:      { action: index }

default:
  url:        /:module/:action/*
