all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=sfforo'
      username: sfforo
      password: sfforo
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=sfforo_test'
      username: sfforo
      password: sfforo
