Seccion:
  actAs:
    Sluggable:
      unique: true
      fields: [nombre]
      canUpdate: true
  columns:
    nombre:             { type: string(255), notnull: true }
    descripcion:        { type: string(255), notnull: true }

Mensaje:
  actAs:                [Timestampable]
  columns:
    contenido:          { type: clob, notnull: true }
    id_autor:           { type: integer, notnull: true }
  relations:
    Autor:
      class:            sfGuardUser
      local:            id_autor
      foreign:          id

MensajeTema:
  inheritance:
    type:               concrete
    extends:            Mensaje
  actAs:
    Sluggable:
      unique: true
      fields: [titulo]
      canUpdate: true
  columns:
    titulo:             { type: string(255), notnull: true }
    id_seccion:         { type: integer, notnull: true }
    fijo:               { type: boolean, notnull: true }
  relations:
    Seccion:
      local:            id_seccion
      foreign:          id
      foreignAlias:     Temas
    creado_por:
      class:            sfGuardUser
      local:            id_autor
      foreign:          id
      foreignAlias:     Temas

MensajeRespuesta:
  inheritance:
    type:               concrete
    extends:            Mensaje
  columns:
    id_tema:            { type: integer, notnull: true }
    id_seccion:         { type: integer, notnull: true }
  relations:
    MensajeTema:
      local:            id_tema
      foreign:          id
      foreignAlias:     Respuestas
    Seccion:
      local:            id_seccion
      foreign:          id
      foreignAlias:     Respuestas
    creado_por:
      class:            sfGuardUser
      local:            id_autor
      foreign:          id
      foreignAlias:     Respuestas